image: oarteam/batsim_ci:latest

variables:
  GIT_SUBMODULE_STRATEGY: none

stages:
  - unique

unique:
  stage: unique
  script:
    # build and run stuff
    - nix build .#ci-batsim-internal-test -o result-int
    - nix build .#ci-batsim-edc-test-from-internal-gcda -o result-ext
    - nix build .#ci-batsim-test-coverage-report -o result-cov
    - cat result/file-summary.txt

    # fail if any test have failed
    - if [[ "$(cat ./result-ext/pytest_returncode)" -ne 0 ]] ; then echo "pytest returned non-zero, aborting" ; exit 1 ; fi
