language: nix

sudo: false

services:
  - docker

before_install:
 - nix --version
 - docker --version

install:
 - nix-env -iA cachix -f https://cachix.org/api/v1/install
 - cachix use batsim

script:
 - nix-build -A batsim-docker-master 'https://github.com/oar-team/nur-kapack/archive/master.tar.gz' -o ./tarball
 - docker load -i ./tarball

deploy:
 - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_LOGIN}" --password-stdin
 - docker push oarteam/batsim:latest
