language: nix

sudo: false

script:
 - nix --version
 - docker --version
 - nix-env -iA cachix -f https://cachix.org/api/v1/install
 - cachix use batsim
 - nix-build -A batsim-docker-master 'https://github.com/oar-team/nur-kapack/archive/master.tar.gz' -o ./tarball
 - docker load -i ./tarball
