name: Notify Mattermost
on:
  pull_request:
    types: [opened, edited, closed, reopened]
  issues:
    types: [opened, edited, deleted, closed, reopened, locked, unlocked]
  issue_comment:
    types: [created, edited]
jobs:
  notify-mattermost:
    name: Notify Mattermost
    runs-on: ubuntu-latest
    steps:
      - name: Generate pull request message (any)
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "Something happened about a pull request? ${{ github.event.payload.action }}"
      - name: Generate issue message (any)
        if: ${{ github.event_name == 'issue' }}
        run: |
          echo "Something happened about an issue? ${{ github.event.payload.action }}"

      - name: Generate issue_comment message (any)
        if: ${{ github.event_name == 'issue_comment' }}
        run: |
          echo "Something happened about an issue_comment"
      - name: Generate issue_comment message (created)
        if: ${{ github.event_name == 'issue_comment' && github.event.payload.action == 'created' }}
        run: |
          echo "An issue_comment has been created"
      - name: Generate issue_comment message (edited)
        if: ${{ github.event_name == 'issue_comment' && github.event.payload.action == 'edited' }}
        run: |
          echo "An issue_comment has been edited"
      # - uses: mattermost/action-mattermost-notify@master
      #   env:
      #     MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
