name: Notify Mattermost
on:
  pull_request:
    types: [opened, edited, closed, reopened]
  issues:
    types: [opened, edited, deleted, closed, reopened, locked, unlocked]
  issue_comment:
    types: [created, edited]
jobs:
  notify-mattermost:
    name: Notify Mattermost
    runs-on: ubuntu-latest
    steps:
      - name: Generate pull request message (any)
        if: ${{ github.event_name == 'pull_request' }}
        env:
          ACTION_TYPE: ${{ github.event.action }}
          AUTHOR_LOGIN: ${{ github.event.pull_request.user.login }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          echo "${AUTHOR_LOGIN} ${ACTION_TYPE} [pull request ${PR_NUMBER} (${PR_TITLE})](${PR_URL})"

      - name: Generate issue message (any)
        if: ${{ github.event_name == 'issue' }}
        run: |
          echo "Something happened about an issue? ${{ github.event.action }}"

      - name: Generate issue_comment message (any)
        if: ${{ github.event_name == 'issue_comment' }}
        env:
          ACTION_TYPE: ${{ github.event.action }}
          AUTHOR_LOGIN: ${{ github.event.comment.user.login }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          echo "${AUTHOR_LOGIN} ${ACTION_TYPE} a comment on [issue ${ISSUE_NUMBER} (${ISSUE_TITLE})](${ISSUE_URL})"

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github.event) }}
        run: echo "$GITHUB_CONTEXT"
      # - uses: mattermost/action-mattermost-notify@master
      #   env:
      #     MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
